@extends('layouts.app')
@section('content')  


@section('x_content') 


		<head>
			<link rel="stylesheet" type="text/css" href="style.css"/>
			</head>
			
		
			<img style="position:absolute;top:0.57in;left:0.43in;width:7.82in;height:10.43in" src="/css/workflow/images/OutDocument/vi_1.png" />
			<div style="position:absolute;top:2.17in;left:0.45in;width:1.79in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Nombre:        </span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Área/ Sección/ Programa:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:2.17in;left:5.71in;width:1.02in;line-height:0.18in;"><DIV style="position:relative; left:0.53in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Cargo:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Coordinación:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:2.75in;left:0.45in;width:0.92in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Justificación:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:3.49in;left:0.84in;width:0.29in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">No.</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:3.49in;left:1.69in;width:0.83in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">CANTIDAD</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:3.49in;left:2.77in;width:0.63in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">UNIDAD</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:3.72in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">1</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:3.96in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">2</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:4.20in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">3</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:4.44in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">4</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:4.68in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">5</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:4.92in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">6</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:5.16in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">7</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:5.40in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">8</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:5.64in;left:0.93in;width:0.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">9</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:5.88in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">10</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:6.12in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">11</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:6.36in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">12</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:6.60in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">13</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:6.84in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">14</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:7.08in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">15</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:7.32in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">16</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:7.58in;left:0.88in;width:0.21in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">17</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:7.82in;left:0.45in;width:1.48in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:AFAMDH+ArialMT;color:#000000">Proveedores sugeridos:</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:8.25in;left:3.49in;width:0.74in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">SOLICITA</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:8.25in;left:5.12in;width:0.82in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">AUTORIZA</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:8.25in;left:6.75in;width:0.61in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">RECIBE</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:8.47in;left:2.80in;width:0.56in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">FECHA</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:8.88in;left:0.45in;width:4.61in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">Espacio exclusivo para el Asistente de Gestión Administrativa:</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.09in;left:0.45in;width:1.19in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Tipo de solicitud:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.09in;left:2.68in;width:0.86in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Consumo__</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.09in;left:3.49in;width:0.83in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Inversión__</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.29in;left:0.45in;width:1.54in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Proveedor autorizado:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.29in;left:2.68in;width:0.39in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Si __</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.29in;left:3.49in;width:0.45in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">No __</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.50in;left:0.45in;width:1.45in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Aprobado en comité:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.50in;left:2.68in;width:0.39in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Si __</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.50in;left:3.49in;width:0.45in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">No __</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:9.50in;left:5.17in;width:1.13in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Fecha________</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:10.12in;left:0.45in;width:3.89in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">Recibí los elementos solicitados en este documento:</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:10.35in;left:0.45in;width:0.59in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Nombre</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:10.35in;left:4.56in;width:0.50in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Cargo:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:10.35in;left:6.75in;width:1.30in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Fecha: _________</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:10.59in;left:0.45in;width:6.75in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">Observaciones: ___________________________________________________________________</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:0.58in;left:3.63in;width:2.54in;line-height:0.19in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">Formato de Requisición Interna</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:3.49in;left:4.84in;width:2.07in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">DESCRIPCIÓN DETALLADA</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:1.68in;left:3.54in;width:1.64in;line-height:0.19in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:AGCIGS+Arial-BoldMT;color:#000000">FUNDACION ALUNA</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:AGCIGS+Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:1.92in;left:3.74in;width:1.23in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:AFAMDH+ArialMT;color:#000000">NIT: 806.014.972-9</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:2.75in;left:4.85in;width:1.25in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">No hay existencia</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:1.04in;left:1.84in;width:2.97in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000">Departamento: Administrativo y Financiero</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:1.37in;left:1.53in;width:2.12in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000">Código del formato: AF-001-01</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:8.01in;left:2.77in;width:0.62in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000">FIRMAS</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:AFAMDH+ArialMT;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:1.37in;left:5.12in;width:0.94in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000">Página 1 de 1</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000"> </span><br/></SPAN></div>
			<div style="position:absolute;top:1.04in;left:5.12in;width:2.84in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000">Coordinación: Administrativa y financiera</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:BAOWMC+Calibri;color:#000000"> </span><br/></SPAN></div>
			<img style="position:absolute;top:2.35in;left:1.51in;width:3.59in;height:0.01in" src="/css/workflow/images/OutDocument/vi_2.png" />
			<img style="position:absolute;top:2.53in;left:2.65in;width:2.44in;height:0.01in" src="/css/workflow/images/OutDocument/vi_3.png" />
			<img style="position:absolute;top:0.57in;left:1.50in;width:0.01in;height:1.10in" src="/css/workflow/images/OutDocument/vi_4.png" />
			<img style="position:absolute;top:2.75in;left:2.64in;width:0.01in;height:0.19in" src="/css/workflow/images/OutDocument/vi_5.png" />
			<img style="position:absolute;top:1.01in;left:5.08in;width:0.01in;height:0.67in" src="/css/workflow/images/OutDocument/vi_6.png" />
			<img style="position:absolute;top:8.20in;left:0.43in;width:2.23in;height:0.01in" src="/css/workflow/images/OutDocument/vi_7.png" />
			<img style="position:absolute;top:10.54in;left:1.51in;width:1.96in;height:0.01in" src="/css/workflow/images/OutDocument/vi_8.png" />
			<img style="position:absolute;top:0.56in;left:0.41in;width:0.01in;height:10.45in" src="/css/workflow/images/OutDocument/vi_9.png" />
			<img style="position:absolute;top:3.46in;left:1.50in;width:0.01in;height:4.32in" src="/css/workflow/images/OutDocument/vi_10.png" />
			<img style="position:absolute;top:0.57in;left:8.23in;width:0.01in;height:10.43in" src="/css/workflow/images/OutDocument/vi_11.png" />
			<img style="position:absolute;top:7.78in;left:5.08in;width:0.01in;height:0.87in" src="/css/workflow/images/OutDocument/vi_12.png" />
			<img style="position:absolute;top:3.46in;left:2.64in;width:0.01in;height:5.19in" src="/css/workflow/images/OutDocument/vi_13.png" />
			<img style="position:absolute;top:3.46in;left:3.45in;width:0.01in;height:5.19in" src="/css/workflow/images/OutDocument/vi_14.png" />
			<img style="position:absolute;top:7.78in;left:6.72in;width:0.01in;height:0.87in" src="/css/workflow/images/OutDocument/vi_15.png" />
			<img style="position:absolute;top:0.56in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_16.png" />
			<img style="position:absolute;top:0.99in;left:1.51in;width:6.73in;height:0.01in" src="/css/workflow/images/OutDocument/vi_17.png" />
			<img style="position:absolute;top:1.22in;left:1.51in;width:6.73in;height:0.01in" src="/css/workflow/images/OutDocument/vi_18.png" />
			<img style="position:absolute;top:1.66in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_19.png" />
			<img style="position:absolute;top:2.09in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_20.png" />
			<img style="position:absolute;top:2.35in;left:6.72in;width:1.52in;height:0.01in" src="/css/workflow/images/OutDocument/vi_21.png" />
			<img style="position:absolute;top:2.53in;left:6.72in;width:1.52in;height:0.01in" src="/css/workflow/images/OutDocument/vi_22.png" />
			<img style="position:absolute;top:2.74in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_23.png" />
			<img style="position:absolute;top:2.92in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_24.png" />
			<img style="position:absolute;top:3.19in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_25.png" />
			<img style="position:absolute;top:3.45in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_26.png" />
			<img style="position:absolute;top:3.67in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_27.png" />
			<img style="position:absolute;top:3.91in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_28.png" />
			<img style="position:absolute;top:4.15in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_29.png" />
			<img style="position:absolute;top:4.39in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_30.png" />
			<img style="position:absolute;top:4.63in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_31.png" />
			<img style="position:absolute;top:4.87in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_32.png" />
			<img style="position:absolute;top:5.11in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_33.png" />
			<img style="position:absolute;top:5.35in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_34.png" />
			<img style="position:absolute;top:5.59in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_35.png" />
			<img style="position:absolute;top:5.83in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_36.png" />
			<img style="position:absolute;top:6.07in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_37.png" />
			<img style="position:absolute;top:6.31in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_38.png" />
			<img style="position:absolute;top:6.55in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_39.png" />
			<img style="position:absolute;top:6.79in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_40.png" />
			<img style="position:absolute;top:7.03in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_41.png" />
			<img style="position:absolute;top:7.27in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_42.png" />
			<img style="position:absolute;top:7.51in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_43.png" />
			<img style="position:absolute;top:7.77in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_44.png" />
			<img style="position:absolute;top:7.99in;left:0.43in;width:2.23in;height:0.01in" src="/css/workflow/images/OutDocument/vi_45.png" />
			<img style="position:absolute;top:8.20in;left:3.47in;width:4.78in;height:0.01in" src="/css/workflow/images/OutDocument/vi_46.png" />
			<img style="position:absolute;top:8.42in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_47.png" />
			<img style="position:absolute;top:8.64in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_48.png" />
			<img style="position:absolute;top:8.85in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_49.png" />
			<img style="position:absolute;top:9.88in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_50.png" />
			<img style="position:absolute;top:10.09in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_51.png" />
			<img style="position:absolute;top:10.54in;left:5.09in;width:1.64in;height:0.01in" src="/css/workflow/images/OutDocument/vi_52.png" />
			<img style="position:absolute;top:10.99in;left:0.43in;width:7.82in;height:0.01in" src="/css/workflow/images/OutDocument/vi_53.png" />
			<img style="position:absolute;top:0.70in;left:0.49in;width:0.92in;height:0.74in" src="/css/workflow/images/OutDocument/ri_1.png" />
		
					<!-- ************************************************************************** -->

	
@stop
    
@stop

 